language: go

go:
  - "1.14"

services:
  - docker

env:
  - GO_BUILD="go build" PHPCONFIG_PATH="/home/travis/.phpenv/shims/php-config"

script:
  - make test

cache:
  directories:
    - /home/travis/gopath/pkg
